lib/components/Checkbox/index.js
Add `onChange` and `name` properties to `Checkbox` component
=> Make `Checkbox` compatible with `Formik` framework

lib/components/Modal/index.js
Provide a prop to hide the footer action buttons
=> Provide attribute to hide modal footer action buttons

.github/ci/chromatic.yml
Add github actions for running chromatic test
=> Add GH actions for running chromatic test

.github/workflows/npmPublish.yml
Fix npm publish workflow
>
> If this PR implements changes related to one or more Trello tickets please add them here:
=> Bugfix: Fix npm publish workflow

package-lock.json, package.json
The styled-components version in peerDependencies is quite low.
Update it to the latest version.
no
>
> - What manual steps have you performed to ensure its functioning …
=> fix: update styled-components version to 4.4.0

lib/components/Modal/index.js
>
>
> If this PR implements changes related to one or more Trello tickets please …
=> made bug fix for modal height

.eslintrc, lib/components/Badge/Badge.stories.js, lib/components/Button/Button.stories.js, lib/components/Card/index.js, lib/components/Notification/Notification.stories.js, lib/components/TextInput/TextInput.stories.js, lib/components/TextInput/index.js, package-lock.json, package.json
- Provide a way to do number validation in base text input component
- Fixes eslint issues
- Fixes eslint config
Manual, with storybook
> If this PR implements changes related to one or more Trello tickets please add them here:
=> Feat - Introduce Text input with number validation

lib/components/Modal/index.js, lib/components/Modal/readme.md
The key press is working. But confirmAction and cancelAction may not be provided in props.
Fix the issue and add Readme for Modal.
Please feel free to update the readme file.
No.
>
> - Is it unit tested? If not, …
=> fix: Modal keypress for confirmAction and cancelAction, add Readme

lib/components/Modal/index.js
Add height property for Modal.
No.
>
> If this PR implements changes related to …
=> feat: add height for Modal

lib/components/Header/index.js, lib/components/MobileNav/index.js, lib/components/Notification/index.js, lib/components/Popover/index.js, lib/components/TextInput/index.js, lib/components/Tooltip/index.js
Update PropTypes for components to eliminate warnings from mapper.
Also, change how TextInput pass in numberProps to Input, to remove the DOM attribute warning.
Could not fix the PropType for Card.
We are passing in too many different types of children to Card in mapper.
> Explain how to test the changes in …
=> fix: update PropTypes for components

lib/components/Card/index.js
Change Card children PropTypes to the right one:
Any react node or an array of node
>
> - What manual steps have you performed to ensure its functioning correctly when …
=> fix: change card children type to any react node or array of node

lib/components/Card/index.js
Fix PropType for changeValue in Card.
>
> If this PR implements changes related …
=> fix: changeValue PropTypes in Card, should be string

lib/components/Dialogue/index.js
Fix proptypes for Dialogue.
>
> If this PR implements changes related to one or …
=> fix: update Dialogue proptypes for children

lib/components/Modal/index.js
Fix issue for using keyboard closing Modal.
onConfirm function may not be provided. (mapper - notes modal is hiding the footer, so no need to use the onConfirm in Modal)
>
> - …
=> fix: Modal may not have onConfirm func provided

lib/components/Layout/index.js, lib/components/Tooltip/Tooltip.stories.js, lib/components/Tooltip/index.js, lib/components/Tooltip/readme.md
Ported Tooltip component over to Storybook (created Tooltip.stories.js, modified index.js)
=> Tooltip component stories for Storybook.

lib/components/Card/Card.stories.js, lib/components/Card/index.js, lib/components/Tooltip/Tooltip.stories.js, lib/components/Tooltip/index.js
Ported Card component to Storybook. Some changes to placeholder content to make things simpler/clearer. Specified "arrowUp" and "arrowDown" for changeIcon prop (instead of bool) to make usage clearer.
=> Card component stories

lib/components/Badge/Badge.stories.js, lib/components/Badge/index.js, lib/components/Button/Button.stories.js, lib/components/Button/index.js
Badge component ported to Storybookj. Button bug fix: fixed the "no component" display, properties and usage guideline text are now displayed..
=> Ported Badge to Storybook. Bug fixes and added stories for Button.

lib/components/Checkbox/Checkbox.stories.js, lib/components/Checkbox/index.js
Porting Checkbox to Storybook.
=> Porting Checkbox to Storybook.

lib/components/Divider/Divider.stories.js, lib/components/Divider/index.js, lib/components/Expandable/Expandable.stories.js, lib/components/Expandable/index.js, lib/components/Header/Header.stories.js, lib/components/Header/index.js, lib/components/Icon/Icon.stories.js, lib/components/Icon/index.js, lib/components/Loading/Loading.stories.js, lib/components/Loading/index.js, lib/components/Notification/Notification.stories.js, lib/components/Notification/index.js, lib/components/Tooltip/Tooltip.stories.js
Ported to Storybook: Divider, Expandable, Header, Icon, Loading. The syntax for Header is now different (uses simpler tags).
=> Misc component stories

lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js, lib/components/ProgressBar/ProgressBar.stories.js, lib/components/ProgressBar/index.js, lib/components/RadioButton/RadioButton.stories.js, lib/components/RadioButton/index.js
Components ported to Storybook: Popover, ProgressBar, RadioButton
Checked that they still work in Styleguidist
=> Popover component stories

.github/workflows/security.yml, installGitSecrets.sh, package-lock.json, package.json
Install git-secrets if it doesn't already exist in target machine and scans the repo for exposed secrets. Note that this can be expanded to include any custom lists of secrets that we should cater for outside of AWS
- Install git-secrets if it doesn't already exist. Register git-secrets to analyse AWS secrets in the repo
- Fix up Husky config, precommit in scripts is deprecated
- Add gitallowed to allow fake secret keys used in local dev
- Only run security related checks on pre-push instead of pre-commit (npm audit and secret key scans)
>
> - What testing have you …
=> SEC-207 - Implement secret key scans

package-lock.json, package.json
Fix npm audit security warnings: serialize-javascript
>
> If this PR implements …
=> fix: npm audit security warning: serialize-javascript version must >= 2.1.1

packages/orca-design-system/lib/globalStyles.js, packages/orca-design-system/package-lock.json, packages/orca-design-system/package.json, packages/orca-design-system/styleguide.config.js
Upgrading styled-components for Orca!
=> fix: Upgrade to styled-components v5, move font @import

packages/orcs-design-system/lib/components/Avatar/index.js
=> refactor Avatar component

packages/orcs-design-system/__mocks__/@fortawesome/react-fontawesome.js, packages/orcs-design-system/__mocks__/fileMock.js, packages/orcs-design-system/__mocks__/styleMock.js, packages/orcs-design-system/lib/components/Dialogue/Dialogue.stories.js, packages/orcs-design-system/lib/components/Dialogue/Dialogue.test.js, packages/orcs-design-system/lib/components/Modal/Modal.test.js, packages/orcs-design-system/lib/components/Modal/index.js, packages/orcs-design-system/lib/components/Select/index.js, packages/orcs-design-system/package-lock.json, packages/orcs-design-system/package.json, packages/orcs-design-system/webpack.config.js
=> setup unit test infra and add tests for Modal and Dialogue

packages/orcs-design-system/lib/components/Avatar/Avatar.stories.mdx, packages/orcs-design-system/lib/components/Box/Box.stories.mdx, packages/orcs-design-system/lib/components/Box/index.js, packages/orcs-design-system/lib/systemtheme.js
Simplified shadow and border for box. Added shadows to systemtheme.
=> Fixes to box

packages/orcs-design-system/lib/index.js
Quick fix to index.js to fix compile error
=> Remove Strong, add Small to exports

packages/orcs-design-system/lib/components.test.js, packages/orcs-design-system/lib/components/Box/index.js, packages/orcs-design-system/lib/components/Spacer/index.js, packages/orcs-design-system/lib/components/Typography/Typography.stories.mdx, packages/orcs-design-system/package-lock.json, packages/orcs-design-system/package.json
- Fixes to Spacer props, added in wrapper to prevent sometimes overriding children's other props, removed default margin
- Fixes to Box default props
- Upgrade to latest Storybook version
=> Box and Spacer fixes and updates

packages/orcs-design-system/.storybook/manager-head.html, packages/orcs-design-system/.storybook/orcsTheme.js, packages/orcs-design-system/lib/GlobalStyles.js, packages/orcs-design-system/lib/components/Avatar/Avatar.stories.js, packages/orcs-design-system/lib/components/Button/Button.stories.mdx, packages/orcs-design-system/lib/components/Card/Card.stories.mdx, packages/orcs-design-system/lib/components/Spacer/Spacer.stories.mdx, packages/orcs-design-system/package.json
- Update docs and components for new Spacer default
- Remove @import in GlobalStyles (was causing build to fail at injecting CSS)
=> Fixes for building Storybook

packages/orcs-design-system/README.md, packages/orcs-design-system/lib/components.test.js, packages/orcs-design-system/lib/components/Avatar/index.js, packages/orcs-design-system/lib/components/Box/index.js, packages/orcs-design-system/lib/components/Header/Header.stories.mdx, packages/orcs-design-system/lib/components/Header/index.js, packages/orcs-design-system/lib/components/Icon/index.js, packages/orcs-design-system/lib/components/Popover/index.js, packages/orcs-design-system/lib/components/Spacer/index.js, packages/orcs-design-system/lib/components/StyledLink/index.js, packages/orcs-design-system/lib/index.js, packages/orcs-design-system/lib/systemtheme.js, packages/orcs-design-system/package-lock.json, packages/orcs-design-system/package.json
- Update Header with new components and styled-system syntax
- Fix StyledLink props issues
- Improve Spacer behaviour (now inherits parent Flex styles and allows to be used properly in Flex)
- Various fixes to address errors in console
=> Nav-related fixes

packages/orcs-design-system/lib/components/Sidebar/index.js, packages/orcs-design-system/lib/systemtheme.js
Refactor Sidebar to be consistent with styled-system theme and functions.
=> Sidebar update

packages/orcs-design-system/lib/components/Loading/Loading.stories.js, packages/orcs-design-system/lib/components/Loading/Loading.stories.mdx, packages/orcs-design-system/lib/components/Loading/index.js, packages/orcs-design-system/lib/components/Spacer/index.js, packages/orcs-design-system/lib/systemtheme.js
- Documentation updates and prop fixes for Loading
- Added theme to Spacer
- Added t-shirt size aliases to space array in systemtheme
=> Documentation updates - Loading

packages/orcs-design-system/lib/components/Spacer/index.js, packages/orcs-design-system/package-lock.json
Refactor Spacer with a wrapper SpacerBox div that will take the props instead of passing them to child.
=> Update Spacer component to pass props to wrapper instead of child

packages/orcs-design-system/lib/components/RadioButton/RadioButton.stories.js, packages/orcs-design-system/lib/components/RadioButton/index.js
=> Radiobutton refactor

CNAME, README.md
Adds the `CNAME` file to set the custom domain for this repo. Saving a custom domain in settings is expected to create a commit for the `CNAME` file but that is either not happening it is being subsequently overwritten.
Also proposes a change to the `README`. My first commit attempt failed because I had to go into each of the packages and `npm i`. If that's not required we can change the `README` fo the correct steps.
> If this PR introduce some interaction or animation change please also add GIF with how it behaves. Don't forget …
=> Adds cname

packages/orcs-design-system/lib/components/Button/index.js, packages/orcs-design-system/package-lock.json, packages/orcs-design-system/package.json
Refactors `Button` to use styled-system. Allows for usage of both `data-testid="test"` and `dataTestId="test"` for the `data-testid` attribute.
=> Button refactor

packages/orcs-design-system/lib/components/Button/index.js, packages/orcs-design-system/lib/components/Typography/index.js
- Fix for Button height and padding
- Fix for Small typography
=> Button refactor misc fixes

packages/orcs-design-system/lib/components/ActionsMenu/index.js
=> fixed actionsMenu close issue

packages/orcs-design-system/lib/__snapshots__/Storyshots.test.js.snap, packages/orcs-design-system/lib/components/ActionsMenu/index.js
Improve the ActionsMenu for:
- clicking to close
- right click (context menu) stay
=> fix: imporve ActionsMenu for clicking and right click

package-lock.json, package.json, packages/orcs-design-system/lib/__snapshots__/Storyshots.test.js.snap, packages/orcs-design-system/lib/components/Flex/index.js, packages/orcs-design-system/lib/components/Grid/index.js, packages/orcs-design-system/lib/components/Modal/Modal.mdx, packages/orcs-design-system/lib/components/Modal/Modal.stories.js, packages/orcs-design-system/lib/components/Modal/index.js, packages/orcs-design-system/lib/components/Select/Select.stories.js, packages/orcs-design-system/lib/components/Select/index.js, packages/orcs-design-system/lib/components/Sidebar/index.js, packages/orcs-design-system/lib/components/Typography/index.js, packages/orcs-design-system/lib/hooks/keypress.js, packages/orcs-design-system/package-lock.json, packages/orcs-design-system/package.json
**DESIGN-239 and DESIGN-218 fixes:**  
- Fix `Select` styling -- border-radius, colour, padding
- Fix `Small` element and props
- Add uppercase prop to `Typography` 
- Fix `Grid` and `Flex` default props
- Fix `Sidebar` filter badge alignment
**Jira cards:**
https://orchestrated.atlassian.net/browse/DESIGN-239
https://orchestrated.atlassian.net/browse/DESIGN-218
=> Usability fixes

packages/orcs-design-system/lib/__snapshots__/Storyshots.test.js.snap, packages/orcs-design-system/lib/components/Modal/Modal.mdx, packages/orcs-design-system/lib/components/Modal/Modal.stories.js, packages/orcs-design-system/lib/components/Modal/index.js, packages/orcs-design-system/lib/components/TextArea/index.js
=> enhanced modal to include header, footer and scrollable content

packages/orcs-design-system/lib/components/Badge/index.js, packages/orcs-design-system/lib/components/Notification/index.js, packages/orcs-design-system/lib/components/TextArea/index.js, packages/orcs-design-system/lib/systemtheme.js
=> New colour palette YIEWWWW

packages/orcs-design-system/lib/components/DatePicker/DatePicker.stories.js, packages/orcs-design-system/lib/components/DatePicker/index.js, packages/orcs-design-system/lib/components/Modal/index.js
=> fix: pass down datepicker props

packages/orcs-design-system/lib/components/Header/index.js
Add id to logout button. => Make it easier to be targeted in testing.
=> feat: add id to logout button in header

package-lock.json, package.json
Bumping major version, to avoid confusion with previous version mess related to orca and orcs.
Going forward we will be more serious about versioning and use minor/major versions to indicate breaking changes, etc.
=> Bumping major version to v2

README.md, lib/components/ActionsMenu/ActionsMenu.mdx, lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js, package.json
=> Adds new advanced version of actionsMenu

lib/components.test.js, lib/components/ActionsMenu/ActionsMenu.mdx, lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js, lib/index.js
feat: export ActionsMenuHeading component
=> feat: export ActionsMenuHeading component

lib/components/TextArea/TextArea.stories.js, lib/components/TextArea/index.js
=> fix: pass autoFocus down to TextArea

lib/components/Notification/index.js
Remove the onDismiss in NotificationWrapper => It does nothing as there is no events called dismiss
- this is a callback function for closing the notification
=> fix: remove react warning for onDismiss

lib/components/Notification/index.js
onDismiss may not be provided in the props.
=> fix: onDismiss may not be provided - add a check

package-lock.json, package.json
v4 has removed the UNSAFE react functions, so good to update.
It seems there is no breaking change for our use cases.
=> feat: update react-select to v4.1.0

lib/components/Avatar/Avatar.mdx, lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
Hide the extra `div`s if title / subtitle not provided
=> TFDEV-1540 fix: hide title / subtitle divs if value not provided

lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
=> feat: add uppercase prop to avatar component

lib/components/Popover/Popover.mdx, lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js
Make the links inside tooltip clickable.
Add prop to toggle whether select all or not
=> fix: make links inside tooltip clickable

lib/components/Select/Select.mdx, lib/components/Select/Select.stories.js, lib/components/Select/index.js
feat: handle isFixed flag in select styles
=> feat: handle isFixed flag in select styles

package-lock.json, package.json
=> audit-ci fix, bump moment

README.md
=> update readme with publishing instructions

lib/components/Flex/index.js, lib/components/Select/index.js
- Add shouldForwardProp config to select component styled divs to remove warning re invalid div attributes (width, height etc)
- Use styled-system props to ensure proptypes validation passes for valid styled-system properties
=> Eliminate warnings in downstream projects

lib/components/Checkbox/Checkbox.mdx, lib/components/Checkbox/index.js
fix: improve checkbox animation - only run when checked / unchecked
=> fix: improve checkbox animation - only run when checked / unchecked

lib/components/Avatar/Avatar.mdx, lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
Adds a tag variant and shape to the avatar component as shown in screenshot below:
=> Added tag variant to avatar

lib/components/Tag/Tag.stories.js, lib/components/Tag/index.js
feature: add click event handler for Tag
=> feature: add click event handler for Tag

lib/components/Select/index.js, lib/components/Tag/index.js
fix: tag font size, add updateStyles to allow customise select styles
=> fix: tag font size, add updateStyles to allow customise select styles

lib/components/Avatar/Avatar.mdx, lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
Added support to Avatar component so that it can have custom content as a subtitle.
=> Added custom subtitles to avatar

.github/workflows/ci.yml, .github/workflows/pr.yml, audit-ci.json
=> added njsscan for security issues

lib/components/Avatar/index.js, lib/components/Header/Header.stories.js, lib/components/Header/index.js, lib/components/Select/Select.mdx, lib/components/Select/Select.stories.js, lib/components/Select/index.js, lib/components/StyledLink/index.js, lib/components/TextInput/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js
A bunch of changes and improvements for Orcs.
Namely, modifying header to support app and workspace switcher, adding asyncSelect and some prop enhancements and fixes for a few components.
=> Header app switcher changes + adding AsyncSelect and various other changes

lib/components/Sidebar/index.js
Sidebar tab hover colours were wrong for some reason, have fixed.
=> fixed issue with sidebar hover colours

lib/components/ActionsMenu/ActionsMenu.mdx, lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js, lib/components/Avatar/Avatar.mdx, lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
- Added local time prop and sub-component to Avatar component
- Added Text Button trigger example to ActionsMenu
- Added more flexible directional control of ActionsMenu menu via top, left, right props
- Added width prop for ActionsMenu menu so we can specify a width
=> Some component enhancements

lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js, lib/hooks/keepInView.js
> Stops menu changing position while scrolling screen.
Before:
https://user-images.githubusercontent.com/3412440/231049640-9b36df5e-cff6-43fe-931b-5ce105af5878.mov
After:
https://user-images.githubusercontent.com/3412440/231306394-764a9842-bed9-4a6e-b45c-acbfc3f035ae.mov
=> avoid menu reposition on scroll

lib/hooks/keepInView.js
=> ensure no undefined error checking root bounds

lib/components/Tag/Tag.mdx, lib/components/Tag/Tag.stories.js, lib/components/Tag/index.js
Need to show strikethrough for Tag component
part of the ticket [https://orchestrated.atlassian.net/browse/TPP-468](https://orchestrated.atlassian.net/browse/TPP-468)
=> allow to show strikethrough for Tag

lib/components/Card/Card.stories.js
Added an `arial-label` to the relevant card story.
=> Added aria-label to the card stories [23.1]

lib/components/Notification/index.js
Before:
```html
<div class="Notification__NotificationWrapper-sc-1p26rkq-0 jkQdNM floating centered">
<p class="Notification__NotificationContent-sc-1p26rkq-1 VcKgU">
Centered notification
</p>
<button class="Notification__Close-sc-1p26rkq-2 fyKGhc close-button" tabindex="0">
...
</button>
</div>
```
After:
```html
<div role="alert" class="Notification__NotificationWrapper-sc-1p26rkq-0 jkQdNM floating centered">
<p class="Notification__NotificationContent-sc-1p26rkq-1 VcKgU">
Centered notification
</p>
<button class="Notification__Close-sc-1p26rkq-2 fyKGhc close-button" tabindex="0" aria-label="Close Notification">
...
</button>
</div>
```
=> Add aria labels notifications [34.1]

lib/components/ActionsMenu/index.js, lib/components/ProgressBar/ProgressBar.stories.js, lib/components/ProgressBar/index.js
Before:
```html
<div class="ProgressBar__Background-q9qaaf-0 fhQPpw" style="width: 100%;">
<div class="ProgressBar__Fill-q9qaaf-1 kgfZak" style="width: 40%;"></div>
</div>
```
After:
```html
<div aria-label="Percent Completed" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" class="ProgressBar__Background-q9qaaf-0 fhQPpw" style="width: 100%;">
<div class="ProgressBar__Fill-q9qaaf-1 kgfZak" style="width: 40%;"></div>
</div>
```
=> Add aria tags to progress bars [32.1]

lib/components/SideNav/SideNav.mdx, lib/components/SideNav/SideNav.stories.js, lib/components/SideNav/index.js
Improved sidenav with a few enhancements:
- Passing react router links through correctly
- Passing button functions through correctly
- Bottom aligned icons
- Accessibility
=> Updates to sidenav component

lib/components/SideNav/index.js
=> Made some updates to sidenav component

lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js, lib/components/SideNav/SideNav.mdx, lib/components/SideNav/SideNav.stories.js, lib/components/SideNav/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js
=> SideNav + Popover updates

package-lock.json
Fix one critical vulnerability in `loader-utils`
```
loader-utils  2.0.0 - 2.0.3
Severity: critical
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - https://github.com/advisories/GHSA-3rfm-jhwj-7488
Prototype pollution in webpack loader-utils - https://github.com/advisories/GHSA-76p3-8jx3-jpfq
fix available via `npm audit fix`
node_modules/loader-utils
```
See also https://github.com/orchestrated-io/teamform-app-ui/pull/2812
No other code changes.
=> HELP-6391: fix critical vulnerability

lib/components/SideNav/SideNav.mdx, lib/components/SideNav/SideNav.stories.js, lib/components/SideNav/index.js
* Add a flag `hide` not to display nav items while index of the item in array still persisted
* This is for fixing index is being pointed wrong component when item is hidden
=> add a flag to hide items in side nav

lib/components.test.js, lib/components/TreeNav/TreeNav.mdx, lib/components/TreeNav/TreeNav.stories.js, lib/components/TreeNav/index.js, lib/index.js, package-lock.json, package.json
Using a new tree library that is more recent and up to date, more flexible / easy to use, and also more performant as it has virtualised dom and only loads what's in the parent scroll in view.
We use this tree style navigation across our app and its about time it became a design system component! :)
=> Initial commit for adding new treenav component

lib/components/DatePicker/DatePicker.mdx, lib/components/DatePicker/DatePicker.stories.js, lib/components/DatePicker/index.js, lib/components/Select/Select.mdx, lib/components/Select/Select.stories.js, lib/components/Select/index.js, lib/components/TextArea/TextArea.stories.js, lib/components/TextInput/TextInput.stories.js
Improving form field components to support both invalid and mandatory props.
=> Extending form field components to support invalid and mandatory states properly

lib/components/Avatar/Avatar.stories.js, lib/components/HeaderSimple/HeaderSimple.stories.js, lib/components/Tag/Tag.mdx, lib/components/Tag/Tag.stories.js, lib/components/Tag/index.js
=> Added person avatar option to tag

package-lock.json
Quick update to two packages - `follow-redirects` and `@adobe/css-tools`
=> Vanta moderate risk issues

package-lock.json, package.json
Minor upgrade to `ip` npm package
=> Eliminate medium risk Vanta issue with 'ip' library

.eslintrc, lib/components/Popover/index.js, package-lock.json, package.json
> Adds dismissal of tooltips on Escape key for accessibility 
https://teamform.atlassian.net/browse/DESIGN-664
=> added dismiss on esc for tooltips

.storybook/manager.js, README.md, lib/01-Intro.stories.mdx, package-lock.json, package.json
=> Update orchestrated to teamform in docs

lib/components/ActionsMenu/index.js, lib/components/Modal/Modal.stories.js, lib/components/Modal/index.js, lib/hooks/keypress.js, package-lock.json, package.json
> This improves the keyboard and accessibility of ActionMenus and Modals.
=> improved keyboard usability for action menu and modal

.env.example, .gitignore, README.md, package-lock.json, package.json, scripts/dev.js
> Adds a script for easier local dev between ORCS and any of our projects. See Readme
=> Local Dev server

.env.example, README.md
> Updates readme for the new dev server code.
=> updated readme for nodemon changes

lib/components/ActionsMenu/index.js, package-lock.json, package.json
> When clicking a link from an ActionMenu with a new route render, the ActionMenu is unmounted and the onBlur action is still executed but the wrapperRef is now undefined because it will have been removed from the dom. 
Fixes Sentry error: https://teamform.sentry.io/issues/5130451812/?alert_rule_id=1357827&alert_type=issue&environment=app.teamform.co&notification_uuid=55b35257-beaf-4d0f-86b1-3f0513033551&project=279663&referrer=slack
=> fixed undefined error

lib/components/Divider/index.js, lib/components/SideNav/NavItem.js, lib/components/SideNav/index.js, package-lock.json, package.json
=> made some small refactors to SideNav and NavItem

lib/components/DatePicker/index.js, lib/components/Popover/index.js, package-lock.json, package.json
- Updated styling of Date Range inputs
- Fixed a long standing issue with popover tooltips disappearing when user wants to hover and select toopltip text or click a link in tooltip
=> Date range popover fixes

lib/components/DatePicker/DatePicker.mdx, lib/components/DatePicker/DatePicker.stories.js, lib/components/DatePicker/index.js, lib/components/HeaderSimple/index.js, package-lock.json, package.json
- Fixed mobile layout of header simple with search
- Added styling for DatePicker with showClearDate/s prop
Mobile Header Before:
Mobile Header After:
Added styling for clear dates button:
=> Header and datepicker improvements

lib/components/DatePicker/DatePicker.stories.js, lib/components/DatePicker/index.js, package-lock.json, package.json
=> Fixed datepicker input width

package-lock.json
=> npm audit fix - medium vulnerabilities

lib/components/SideNav/SideNav.stories.js, lib/components/SideNav/index.js, package-lock.json, package.json
=> DRAFT Refactor/side nav

lib/components/Select/index.js, lib/components/SideNav/NavItem.js, lib/components/SideNav/SideNav.mdx, lib/components/SideNav/SideNav.stories.js, lib/components/SideNav/index.js, lib/hooks/usePrevious.js, package-lock.json, package.json
- SideNav needed a few fixes/changes to behave correctly in the app
- We have also refactored and removed duplicate code to make this component simpler
=> Side nav changes and fixes

lib/components/Select/index.js, package-lock.json, package.json
Fixing warnings with propTypes in Select component
=> Fixing prop types for multi value

lib/components.test.js, lib/components/Button/index.js, lib/components/SideNav/NavItem.js, lib/index.js, package-lock.json, package.json
> Exposes button variant colors as an object for reuse elsewhere
=> Tpp 759/button updates for custom icons

lib/components/Table/Table.stories.js, lib/components/Table/getExpandColumnConfig.js, lib/components/Table/index.js, lib/components/Table/muiStyleOverrides.js, package-lock.json, package.json
> allowed expandable column to be searchable with highlighting
=> allowed expandable column to be searchable with highlighting

lib/components.test.js, lib/components/Button/ButtonLink.stories.js, lib/components/Button/index.js, lib/components/StyledLink/StyledLink.stories.js, lib/components/StyledLink/index.js, lib/index.js, package-lock.json, package.json
=> Refactor button and add link button

lib/components/Button/index.js, package-lock.json, package.json
> Allows for overriding width and display for styled button links
=> added styling overrides for ButtonLink

lib/components/Button/index.js, package-lock.json, package.json
=> Hotfix button aria label

lib/components/DatePicker/DatePicker.stories.js, lib/components/DatePicker/index.js, package-lock.json, package.json
- Width prop was not calculating correctly for some elements.
- Changed styling of clearDates button to be more integrated into the input.
=> Changed DatePicker clearDates and width issues

package-lock.json, package.json
=> TPP-801 bump version (conflicted with another patch)

lib/components/StatusDot/StatusDot.stories.js, lib/components/StatusDot/index.js, package-lock.json, package.json
Tweaking some styles to make status dot with icons a bit more accessible to vision impaired users
=> Status dot update

lib/components/ProgressBar/ProgressBar.stories.js, lib/components/ProgressBar/index.js, package-lock.json, package.json
This fixes issue with how progress bar fill width is calculated.
=> Progressbar fix

package-lock.json
https://github.com/orchestrated-io/orcs-design-system/security/dependabot/100
=> Fix vulnerability in fast-loops

lib/components/StyledLink/index.js, package-lock.json, package.json
=> TPP-849 fixed issue where ref was not forwarded on StyleLink

lib/components/ActionsMenu/index.js, lib/components/Modal/index.js, lib/components/Popover/index.js, package-lock.json, package.json
=> Updated zindexes

lib/components/ActionsMenu/index.js, lib/components/Modal/index.js, lib/components/Popover/index.js, lib/utils/floatingUiHelpers.js, package-lock.json, package.json
> Adds utils to determine if ActionMenu or Popover is rendered inside modal to determine zIndex and root portal element
=> TPP 849 fix modal and popover z index issues

lib/components/ActionsMenu/index.js, package-lock.json, package.json
> Wrapper was also getting testid so it was failing some specs.
=> TPP-849 fix data testid for actionmenu

lib/components/ActionsMenu/index.js, lib/components/Popover/index.js, package-lock.json, package.json
>  Adds data-testid for Popover and optional chaining for context retrieved function
=> TPP-849 fix data testid for Popover

lib/components/ActionsMenu/index.js, lib/components/ActionsMenu/useActionMenu.js, lib/components/Popover/index.js, package-lock.json, package.json
=> TPP-849 accessibility for floatin UI

lib/components/ActionsMenu/index.js, lib/components/Popover/index.js, package-lock.json, package.json
=> TPP-849 Added hack to ensure tests run green in teamform-app-ui

lib/components/ActionsMenu/index.js, lib/components/Popover/index.js, package-lock.json, package.json
=> TPP 849 fix tabable children on floatin UI with aria hidden

lib/components/ActionsMenu/index.js, package-lock.json, package.json
> When menu is closed, need to make action menu items non tab-able and hidden for accessibilty. Also needed testid on menu.
=> TPP 849 final touches

lib/components/ActionsMenu/index.js, package-lock.json, package.json
> Updated ActionsMenu FocusTrap props
=> TPP 849 /final touches

lib/components/ActionsMenu/index.js, lib/components/Checkbox/index.js, lib/components/Popover/index.js, lib/components/RadioButton/index.js, package-lock.json, package.json
=> TPP-849 added visibility for markup when popover/actionmenu is closed

lib/components/Popover/index.js, package-lock.json, package.json
=> TPP-849 improve accessibility of popover

lib/components/Icon/index.js, package-lock.json, package.json
=> TPP 849 add forward ref to icon

lib/components/Popover/index.js, package-lock.json, package.json
=> TPP-849 add tab index to popover children

lib/components/Modal/index.js, lib/components/Popover/index.js, package-lock.json, package.json
=> TPP-849 fix modal initial focus

lib/components/Popover/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js, package-lock.json, package.json
Fixed popover tooltip arrow positioning, was a little off.
=> Few small popover fixes

lib/components/Table/const.js, lib/components/Table/getExpandColumnConfig.js, package-lock.json, package.json
[https://teamform.atlassian.net/jira/servicedesk/projects/HELP/queues/custom/8/HELP-7933](https://teamform.atlassian.net/jira/servicedesk/projects/HELP/queues/custom/8/HELP-7933)
Allow to override the first column size
=> allow to override default column size for the first column

lib/components/Popover/index.js, lib/utils/floatingUiHelpers.js, package-lock.json, package.json
=> TPP-879 fix issue where tooltip crashes global bar

lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js, package-lock.json, package.json
=> HELP-7947 popover trigger refs

package-lock.json
Fixes to security vulnerabilities - https://github.com/orchestrated-io/orcs-design-system/security/dependabot
=> PLAT-612: Vanta medium risks

package-lock.json, package.json
See https://github.com/GoogleChrome/workbox/issues/3347#issuecomment-2370153474
Latest high risk security vulnerability
=> Fix security vulnerabilities with older versions of Rollup

lib/components/Tabs/index.js, package-lock.json, package.json
> Adds relevant ARIA roles for tabs component
=> TPP-943 tab aria issues

package-lock.json, package.json
Fix a vulnerability in orcs repo - https://github.com/orchestrated-io/orcs-design-system/security/dependabot
=> Fix cross-spawn vulnerability

lib/components/ActionsMenu/ActionsMenu.animations.js, lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js, lib/components/Select/index.js, lib/components/Tag/Tag.stories.js, lib/components/Tag/index.js, package-lock.json, package.json
**Fixes some Tags bugs:**
- cross not centered:
- tag type wrapping:
- tag wrapping button height not correct:
**ActionsMenu component has been updated to match new design aesthetics + improved animation:**
Old:
https://github.com/user-attachments/assets/1f77c648-1645-4137-aeb7-6929b772ed02
New:
https://github.com/user-attachments/assets/dd307d8f-978d-4155-ad1b-6c9ff819b685
=> ActionsMenu update and tags UI bug fixes

lib/components/Header/Header.styles.js, lib/components/SideNav/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js, package-lock.json, package.json
Fixing an accidental change to old header.
=> Fixing theme issue

lib/components.test.js, lib/components/TabsAlt/TabsAlt.mdx, lib/components/TabsAlt/TabsAlt.stories.js, lib/components/TabsAlt/index.js, lib/index.js, package-lock.json, package.json
Functionally the same as current tabs, just testing out new look/design. Eventually this will replace old tabs and i'll clean up code so we only have one tabs component.
=> New tabs component

lib/components/Table/muiStyleOverrides.js, lib/components/Tag/Tag.stories.js, package-lock.json, package.json
=> Fixed table font size

lib/components/Avatar/index.js, lib/components/Header/Header.styles.js, lib/components/Header/UserMenu.js, lib/components/Header/index.js, lib/components/TabsAlt/index.js, package-lock.json, package.json
=> Some fixes to support new design

lib/components/Header/Header.styles.js, lib/components/Header/UserMenu.js, lib/components/Header/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js, package-lock.json, package.json
=> Updated header styling

package-lock.json, package.json
=> Vanta medium and low risk issues

lib/components/Header/Header.stories.js, lib/components/Header/index.js, package-lock.json, package.json
=> Change to header logo separator

lib/components/FloatingPanels/index.js, package-lock.json, package.json
The clicked panel ID needs to be passed to the consumer to track its state.
=> Add on click callback to floating panel

lib/components/Card/Card.stories.js, lib/components/Card/index.js, lib/components/Tag/Tag.stories.js, package-lock.json, package.json
There was some issues with Card component that was stopping me from rolling out cosmos changes in teamform app. This fixes that.
=> Fixed card component

lib/components/FloatingPanels/FloatingPanels.styles.js, lib/components/FloatingPanels/index.js, package-lock.json, package.json
=> add zIndex to props

lib/components/TabsAlt/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js, package-lock.json, package.json
There was an issue with tab height in the app, this fixes it by explicitly setting a theme value, that we can also access in the app.
=> Tabs alt height fix

lib/components/Badge/Badge.stories.js, lib/components/Badge/index.js, lib/components/Tag/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js, package-lock.json, package.json
=> Badge and colour tweaks

lib/components/ActionsMenu/index.js, lib/components/ProgressBar/index.js
Fixes
https://github.com/orchestrated-io/orcs-design-system/issues/357
https://github.com/orchestrated-io/orcs-design-system/issues/358
=> Fix 357 and 358

lib/components/Tag/index.js, package-lock.json, package.json
Fixes issue with long tags not wrapping when exceeding width of parent container
=> Tags wrapping fix

lib/components/FloatingPanels/index.js, package-lock.json, package.json
Adds event listening to FloatingPanels so that selected panel can be set from anywhere in consumer app.
=> Floating panels events

lib/components/Box/index.js, lib/components/Flex/index.js, lib/components/Notification/Notification.mdx, lib/components/Notification/Notification.stories.js, lib/components/Notification/index.js, lib/components/Tag/Tag.mdx, lib/components/Tag/Tag.stories.js, lib/components/Tag/index.js, lib/systemThemeCollapsed.js, lib/systemtheme.js, package-lock.json, package.json
- Fixes tag wrapping bug
- adds new alt style notification
=> Few component fixes

lib/components/Avatar/index.js, lib/components/Badge/index.js, package-lock.json, package.json
- Fixed avatar margin for large variant
- Fixed badge border/height issue
- Fixed alt badge warning colour
=> Few fixes for avatar and badge components

package-lock.json, package.json
Medium / low security vulnerabilities - https://github.com/orchestrated-io/orcs-design-system/security/dependabot
=> Update playroom and esbuild

lib/components/FloatingPanels/index.js, package-lock.json, package.json
Fixes https://teamform.atlassian.net/browse/HELP-9111
=> Fix issue where the PanelContainer was rendering without any content

lib/components.test.js, lib/components/Avatar/index.js, lib/components/ColorPicker/ColorPicker.mdx, lib/components/ColorPicker/ColorPicker.stories.js, lib/components/ColorPicker/index.js, lib/index.js, package-lock.json, package.json
=> Add new color picker component

lib/components/Avatar/index.js, lib/components/Popover/Popover.mdx, lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js, package-lock.json, package.json
=> Fixed header avatar popover issue

lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js, package-lock.json, package.json
=> Avatar bug fix

lib/components/Icon/index.js, lib/components/SideNavV2/NavItem.js, lib/components/SideNavV2/SideNav.js, lib/components/SideNavV2/__tests__/sections.test.js, lib/components/SideNavV2/components/BaseSection.js, lib/components/SideNavV2/components/CurrentViewSectionPortalTarget.js, lib/components/SideNavV2/components/ExpandedPanel.js, lib/components/SideNavV2/components/PanelControl.js, lib/components/SideNavV2/components/RenderCurrentViewSection.js, lib/components/SideNavV2/sections/SideNavCurrentViewSection.js, lib/components/SideNavV2/sections/SideNavPinnedSection.js, lib/components/SideNavV2/styles/SideNavV2.styles.js, package-lock.json, package.json
This pull request introduces several changes to improve the `Icon` component, enhance the Side Navigation (`SideNavV2`) functionality, and refine the overall user experience. Key updates include simplifying the `Icon` component's implementation, adding responsive behavior to the navigation panel, and improving rendering logic for conditional components. Below is a categorized summary of the most significant changes:
* Replaced the styled-components template literal syntax with the `@styled-system/css` utility for `IconWrapper`, simplifying the code and improving maintainability (`lib/components/Icon/index.js`).
* Removed the `secondaryIcon` prop and its associated logic to streamline the `Icon` component (`lib/components/Icon/index.js`). …
=> TPP-1284/ sidenav UI fixes

lib/assets/Colour/Colour.stories.js, lib/components/Typography/Typography.stories.js
Typography and colour stories was using old syntax and was broken. Have fixed.
=> Stories fix

package-lock.json
Fix critical vulnerability in `form-data` that in rare situations might lead to RCE or other unintended consequences :) 
=> Vanta: critical vuln (form-data)
