orchestrated-io/orcs-design-system

lib/components/Modal/index.js
When the Modal height is too small, the vertical scroll bar will be displayed.
But it's hard to use when there is another scrollable area inside the Modal.
Change container to overflow visible, so that we only display one scroll bar for the inner content,
not on the Modal.
No.
- …
=> fix: make Modal container overflow visible for small Modal Dialog usecase

packages/orcs-design-system/.storybook/main.js, packages/orcs-design-system/.storybook/manager.js, packages/orcs-design-system/lib/components/Grid/Grid.stories.mdx, packages/orcs-design-system/lib/components/Grid/index.js, packages/orcs-design-system/lib/components/Grid/readme.md, packages/orcs-design-system/package-lock.json, packages/orcs-design-system/package.json
Refactor Grid to styled-system using styled-system's built-in grid props. Also removed the storysource addon since it's buggy with MDX at the moment.
=> Grid styled-system component

packages/orcs-design-system/lib/Typography.stories.mdx, packages/orcs-design-system/lib/components/Avatar/Avatar.stories.mdx, packages/orcs-design-system/lib/components/Avatar/index.js, packages/orcs-design-system/lib/components/Typography/index.js, packages/orcs-design-system/lib/systemtheme.js
Avatar and Typography now use themeGet (when needed) and better usage of styled-system functions.
Note, the rgba value in Code was changed to simply warningLightest for ease of use/simplicity.
=> Fixes to Avatar and Typography to use themeGet. Added px to systemtheme.

packages/orcs-design-system/lib/components/TextArea/index.js, packages/orcs-design-system/lib/components/TextInput/index.js
Issue: In team list and people list page, when scroll to the bottom of the page, automatically loading more items, but the page is forced to scroll up.
Reason:
When Input re-rendered, the InputForwarded component is always re-created, which cause the input component to re-render and autoFocus set again.
ref should be passed from outside. and forwardRef should wrap the whole component.
Also, for NumberInput, it's using a special function getInputRef to return the ref, needs to handle that case.
> If this PR implements changes related to one …
=> fix ref issue for TextInput and TextArea

CNAME, packages/orcs-design-system/.storybook/static/CNAME, packages/orcs-design-system/package.json
Moves CNAME for ghpages custom domain into storybook build. This is the correct process to ensure the custom domain is configured when storybook is deployed.
=> moves CNAME into storybook build

packages/orcs-design-system/lib/components/Modal/index.js
in the modal keydown hanlder so Editor doesn't response to enter key, remove the preventDefault call
=> fix: Chrome 83.0.4103.116 stopped the enter key default behaviour

packages/orcs-design-system/lib/components/Modal/index.js
The useOnclickOutside() hook will always add listeners to document to intercept mousedown event, which may cause issue.
Add a disabled flag when Modal is not visible.
This will stop useOnclickOutside add the event listeners.
> You can use [this tool](http://gifbrewery.com/) to …
=> MAPPER-1214 disable onclickoutside handler when modal is invisible

packages/orcs-design-system/lib/components/Modal/index.js, packages/orcs-design-system/lib/hooks/keypress.js
The keydown and keyup event handlers is always attached if Modal is rendered.
This causes several modal close events are triggered if ESC is pressed.
=> fix: only attach event listener when modal is visible

.github/PULL_REQUEST_TEMPLATE.md, lib/components/Modal/index.js, lib/components/Tag/index.js
Fixes an issue with long tags breaking the layout, they will now wrap correctly if they don't fit into parent container width.
=> fixed tag wrapping issue

lib/components/ActionsMenu/ActionsMenu.mdx, lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js, lib/components/Popover/Popover.mdx, lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js, lib/hooks/keepInView.js, package-lock.json, package.json
Adds a custom hook to ensure components with `direction` props are in the view port.
At this stage it simply sets the direction to the exact opposite, e.g. `left` becomes `right`, `top` becomes `bottom` and diagonals like `topLeft` become `bottomRight`.
The hook is used in the `Popover` and `ActionsMenu` for this PR.
=> Tpp 365 move component when hidden

lib/hooks/keepInView.js
> Ensure menu position is not adjusted when scrolling out of view.
Before:
https://user-images.githubusercontent.com/3412440/231641542-b0f1b5eb-e8b1-48be-8d1e-b4be053a36c1.mov
After:
https://user-images.githubusercontent.com/3412440/231641606-565f84bc-dc06-42d7-9396-2501f410999b.mov
=> adds preferred root bounds

lib/components/Icon/Icon.stories.js, lib/components/Icon/index.js
Add a `title` attribute to `Icon` which enables the default `Fontawesome` accessibility capabilites.
When `title` is set an `aria-labelledby` is added to the `<svg />` linked by id to a hidden `<title />` element.
Before:
```html
<svg 
aria-hidden="true"
focusable="false"
data-prefix="fas"
data-icon="angle-down"
class="svg-inline--fa fa-angle-down fa-w-10"
role="img"
xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 320 512">
<path fill="currentColor" d="..."></path>
</svg>
```
After:
```html
<svg 
aria-labelledby="svg-inline--fa-title-tosHB4zVlbMz"
data-prefix="fas"
data-icon="angle-down"
class="svg-inline--fa fa-angle-down fa-w-10"
role="img"
xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 320 512">
<title id="svg-inline--fa-title-tosHB4zVlbMz">Down</title>
<path fill="currentColor" …
```
=> Informative SVG graphic has no alternative text [3.1, 3.2]

lib/components/Avatar/Avatar.mdx, lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
Adds an `alt` attribute to the avatar image. Will use `imageTag` or fallback to the `title` if its a string.
=> Decorative image has no 'alt' attribute [2.1]

lib/components/TextInput/index.js
If `numberProps.prefix` is defined then append it to the label for screen readers.
Before:
```html
<label for="numInput1" class="TextInput__Label-shde0o-3 keTmHt">Currency</label>
```
After:
```html
<label for="numInput1" class="TextInput__Label-shde0o-3 keTmHt">Currency $</label>
```
=> Append currency symbol to label if defined [6.4]

lib/components/Avatar/Avatar.mdx, lib/components/Avatar/Avatar.stories.js, lib/components/Avatar/index.js
This allows passing a `titleLevel` prop which maps to one of the Typography heading elements.
Before:
```html
<Avatar
sizing="large"
title="Ayden Lundgre"
subtitle="Senior Business Analyst"
initials="AL"
/>
<div class="Avatar__TextContent-sc-1wtet2j-1 ZpYup">
<h3 class="Typography__H1-sc-1613j99-0 hnVnbm Avatar__Title-sc-1wtet2j-4 fwEKEl">Ayden Lundgre</h3>
<span class="Typography__Text-sc-1613j99-8 Avatar__Subtitle-sc-1wtet2j-5 zJCfv juppZJ">Senior Business Analyst</span>
</div>
```
After:
```html
<Avatar
sizing="large"
title="Ayden Lundgre"
titleLevel="H1"
subtitle="Senior Business Analyst"
initials="AL"
/>
<div class="Avatar__TextContent-sc-1wtet2j-1 ZpYup">
<h1 class="Typography__H1-sc-1613j99-0 hnVnbm Avatar__Title-sc-1wtet2j-4 fwEKEl">Ayden Lundgre</h1>
<span …
```
=> Allow passing a titleLevel to support any heading tag [8.2]

lib/components/Sidebar/Sidebar.stories.js, lib/components/Sidebar/index.js
Replace sidebar label with a button using `aria-label` and `aria-expanded` attributes.
Before:
```html
<label class="Sidebar__SidebarTab-wr9mfw-2 bDqZrz Sidebar__Badge">
...
</label>
```
After:
```html
<button class="Sidebar__SidebarTab-wr9mfw-2 ljExJn Sidebar__Badge" aria-label="Messages" aria-expanded="true">
...
</button>
```
=> Add aria tags to the sidebar [9.1]

lib/components/Header/index.js
Add relevant `aria-expanded` & `aria-label` attributes.
Before:
```html
<label for="defaultHeader" class="Header__MobileMenuToggle-yf04b-17 cdJYTh">
<span id="hamburger-menu-icon" class="Header__Hamburger-yf04b-18 ivCBYA"></span>
</label>
```
After closed:
```html
<button aria-expanded="false" aria-label="Menu" class="Header__MobileMenuToggle-yf04b-17 dGwaQb">
<span id="hamburger-menu-icon" class="Header__Hamburger-yf04b-18 ivCBYA"></span>
</button>
```
After open:
```html
<button aria-expanded="true" aria-label="Menu" class="Header__MobileMenuToggle-yf04b-17 dGwaQb">
<span id="hamburger-menu-icon" class="Header__Hamburger-yf04b-18 ivCBYA"></span>
</button>
```
Add relevant `aria-hidden` attribute and ensure element is hidden off screen.
Before:
```html
<div aria-hidden="true" …
```
=> Scripted header button not keyboard focusable [17.5]

lib/components/ActionsMenu/ActionsMenu.stories.js, lib/components/ActionsMenu/index.js
Before:
```html
<div class="ActionsMenu__Wrapper-yvbni2-0 iEyrlM">
<button class="ActionsMenu__Control-yvbni2-1 iuQRhd">
<div class="ActionsMenu__Icon-yvbni2-2 hQaqIj"></div>
</button>
<div direction="left" class="ActionsMenu__Menu-yvbni2-3 fBFEua">
<a href="https://orchestrated.io/" class="ActionsMenu__ActionsMenuItem-yvbni2-5 ddewAQ">
Open details page
</a>
<a class="ActionsMenu__ActionsMenuItem-yvbni2-5 ddewAQ" href="/">
Edit
</a>
<button class="ActionsMenu__ActionsMenuItem-yvbni2-5 ddewAQ" type="button">
Remove
</button>
</div>
</div>
```
After:
```html
<div class="ActionsMenu__Wrapper-yvbni2-0 iEyrlM">
<button aria-label="Options Menu" aria-expanded="false" class="ActionsMenu__Control-yvbni2-1 iuQRhd">
<div class="ActionsMenu__Icon-yvbni2-2 hQaqIj"></div>
</button>
<div …
```
=> Add relevant aria labels to the actions menu [27.1 - 27.4]

lib/components/Loading/index.js
Before:
```html
<div class="Loading__LoadingWrapper-sc-195w3kf-0 donmdn">
<svg
xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 512 512"
class="Loading__LoadingIcon-sc-195w3kf-1 SQmHC">
...
</svg>
</div>
```
After:
```html
<div class="Loading__LoadingWrapper-sc-195w3kf-0 donmdn">
<svg
role="image"
aria-label="Loading"
xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 512 512"
class="Loading__LoadingIcon-sc-195w3kf-1 SQmHC">
...
</svg>
</div>
```
=> Apply aria-label & role to Loading [3.1]

lib/components/TextInput/index.js, package-lock.json, package.json
… that was missed yesterday (somehow) - see https://github.com/orchestrated-io/orcs-design-system/pull/227
See https://github.com/orchestrated-io/orcs-design-system/security/dependabot/51
To allow the `overrides` section of package.json you need Node 16.x and NPM > v8.3 React 18.x means that `react-dates` is no longer compatible. Use `--legacy-peer-deps` to install. See https://github.com/react-dates/react-dates/issues/2199
`storybook-deployer` is EOL - see https://github.com/storybook-eol/storybook-deployer
Fix all remaining vulnerabilities
No changes otherwise.
=> HELP-6391: fix outstanding vulnerabilities in ORCS

lib/components/Modal/index.js, package-lock.json, package.json
> There was a race condition for `useOnClickOutside` where by the time the event handler was called, the selected option was removed from the DOM. This caused the `useOnClickOutside` handler to think that the clicked element was outside the element because the element was not a child of `modalRef` any more.
=> HELP-7078 Modal closing on select X click

package-lock.json, package.json
Minor update to remove vulnerable version of `ws` - uses `overrides` (not inherited by other packages).
=> Update ws package via overrides

lib/components/ActionsMenu/index.js, lib/components/Popover/Popover.stories.js, lib/components/Popover/index.js, package-lock.json, package.json
=> TPP-849 fixed click/focus issues

lib/components/ActionsMenu/index.js, lib/components/Popover/index.js, package-lock.json, package.json
> To get around a huge task of fixing tests in `teamform-app-ui` we rendered a "ghost" component to be asserted against. I originally added the floating-ui props to this component. This PR removes those props to prevent recalculations of layout.
=> HELP-8042 slowness due to floating UI

lib/components/ActionsMenu/index.js
There is an extra space for the Action menu if using the current styles for test.
Can change to the sr-only kind of style without any space
Current:
After fix:
=> fix: extra space for Action menu

package-lock.json, package.json
I ran `npm audit fix`, to see if we could get rid of the pending security vulns. I also moved `styled-components` from being a devDep to a standard dep, because ORCS won't build without it. Before:
```
475 packages are looking for funding
run `npm fund` for details
2 low severity vulnerabilities
To address all issues, run:
npm audit fix
Run `npm audit` for details.
```
After:
```
removed 4 packages, changed 7 packages, and audited 2227 packages in 3s
474 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
=> ran npm audit fix

lib/components/Table/index.js, lib/components/Table/muiStyleOverrides.js, package-lock.json, package.json
=> Fix table design

lib/components/Badge/Badge.mdx, lib/components/Badge/Badge.stories.js, lib/components/Badge/index.js, package-lock.json, package.json
=> add altStyle to Badge

lib/components/FloatingPanels/FloatingPanels.styles.js, lib/components/FloatingPanels/Panel.js, lib/components/FloatingPanels/index.js, package-lock.json, package.json
Updates Floating panels UI and behaviour to be a bit cleaner and more in line with Lucy's cosmos mocks. This new approach will also eliminate issues with panel heights and scroll seeing as we are adding more content here in the app.
Before:
After:
=> Floating panels update

lib/components/FloatingPanels/FloatingPanels.mdx, lib/components/FloatingPanels/FloatingPanels.stories.js, lib/components/FloatingPanels/FloatingPanels.styles.js, lib/components/FloatingPanels/Panel.js, lib/components/FloatingPanels/index.js, package-lock.json, package.json
[https://teamform.atlassian.net/browse/TPP-1141](https://teamform.atlassian.net/browse/TPP-1141)
* `centered` makes the panel positioned in center
* `noActiveState` for panel object, when passed, toggling state is not tracked, so that background color is not set when clicked
* `stopToggling` for panel object, when passed, once an icon is clicked, reselecting the same icon doesn't change its state, the background color is persisted
https://github.com/user-attachments/assets/6e759a6a-df2f-4bf5-bccc-1615f3dee715
=> update floating panels component to reuse as control

.storybook/preview.js
From
To
Has the biggest impact on the new FloatingPanels docs
=> better source formatting

lib/components/Popover/index.js
this component is keeping previous floating element and got double tooltip in screen
=> fix: stop render FloatingFocusManager
